name: CI

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: docker login
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      
    - name: build and push
      run: docker build -t jigglebox/fish -f server.Dockerfile . && docker push jigglebox/fish

    - name: save kubeconfig
      uses: digitalocean/action-doctl@master
      env:
        DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.k8s_key }}
      with:
        args: kubernetes cluster kubeconfig show jlr-k8s > $GITHUB_WORKSPACE/.kubeconfig
      
    - name: deploy to k8s
      run: |
        kubectl --kubeconfig=$GITHUB_WORKSPACE/.kubeconfig apply -f $GITHUB_WORKSPACE/path/to/k8s.yaml
        kubectl --kubeconfig=$GITHUB_WORKSPACE/.kubeconfig rollout restart deployment tyler-fish --namespace tyler-fish
